// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    AddFeedModal: typeof import('./src/components/modals/AddFeedModal.vue')['default']
    AddGroupModal: typeof import('./src/components/modals/AddGroupModal.vue')['default']
    Aside: typeof import('./src/components/Aside.vue')['default']
    AsideItemModal: typeof import('./src/components/modals/AsideItemModal.vue')['default']
    DragDownContainer: typeof import('./src/components/DragDownContainer.vue')['default']
    FeedItem: typeof import('./src/components/FeedItem.vue')['default']
    FeedItemContent: typeof import('./src/components/FeedItemContent.vue')['default']
    FeedItemList: typeof import('./src/components/FeedItemList.vue')['default']
    FeedList: typeof import('./src/components/FeedList.vue')['default']
    GalleryModal: typeof import('./src/components/GalleryModal.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonBadge: typeof import('@ionic/vue')['IonBadge']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFab: typeof import('@ionic/vue')['IonFab']
    IonFabButton: typeof import('@ionic/vue')['IonFabButton']
    IonFabList: typeof import('@ionic/vue')['IonFabList']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInfiniteScroll: typeof import('@ionic/vue')['IonInfiniteScroll']
    IonInfiniteScrollContent: typeof import('@ionic/vue')['IonInfiniteScrollContent']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonThumbnail: typeof import('@ionic/vue')['IonThumbnail']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    LazyFeedContent: typeof import('./src/components/LazyFeedContent.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
